### ISSUE TITLE
Internet Explorer - prints entire page

### ISSUE THREAD

**Issue by bedwar2** [menusal/printMe#2]
Have a table inside a div that scrolls.  Using Internet explorer just the page prints not the massive table inside the div.  Using version 10 of IE.

**Comment by menusal** [comment]
Hi.
The plugin use the window.print() method and only printed the visible parts. You can try to print only the table.

**Comment by bedwar2** [comment]
Thanks Dani for the response and for writing this, it's a great idea, very useful.   When I print just the table, it comes out not looking like a table.  That is all the fields are just concatenated next to each other as if it's just one big string.  It works in Chrome but not in IE.
