### ISSUE TITLE
Styles not loaded into print page

### ISSUE THREAD

**Issue by muhghazaliakbar** [menusal/printMe#3]
Hi, i have set css style into my page, but can't loaded on print page.

Here my screenshots:
on html page:
![screenshot_139](https://cloud.githubusercontent.com/assets/8321936/18191154/a02ad8e0-70fa-11e6-8504-fe21d200f3a3.png)

and here on print page:
![screenshot_140](https://cloud.githubusercontent.com/assets/8321936/18191158/ae159454-70fa-11e6-8597-20236dd42444.png)

Here my style on page: 
`<link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.min.css') }}">`
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">`
`<link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.min.css') }}">`
`<link rel="stylesheet" href="{{ asset('dist/css/app.css') }}">`

and my js code:
![screenshot_141](https://cloud.githubusercontent.com/assets/8321936/18191256/92f2a18e-70fb-11e6-85c0-3ee1ecd55c5f.png)

**Comment by menusal** [comment]
Hello.

Chrome supports control of background colour / image printing via CSS. You can set the following CSS property on elements whose background should be printed:

-webkit-print-color-adjust: exact;

**Comment by muhghazaliakbar** [comment]
i have set `-webkit-print-color-adjust: exact;` on `dist/css/app.css` but nothing happens

**Comment by hfunescom** [comment]
Hi! I had the same problem, and I solved It.

I found an error debugging the jquery-printme.js file.

In my example, I was applying that code:
`$("#form").printMe({ "path": "estilo.css" });`

When I debugged the jquery-printme.js file, in the #36 line y saw that code:

```
        for(i in settings.path){
            w.document.write('<link rel="stylesheet" href="'+settings.path+'">');
        }
```

This code was generating the next output:

```
'<link rel="stylesheet" href="e">'
'<link rel="stylesheet" href="s">'
'<link rel="stylesheet" href="t">'
'<link rel="stylesheet" href="i">'
'<link rel="stylesheet" href="l">'
'<link rel="stylesheet" href="o">'
'<link rel="stylesheet" href=".">'
'<link rel="stylesheet" href="c">'
'<link rel="stylesheet" href="s">'
'<link rel="stylesheet" href="s">'
```

So, I commented the "for" cycle, and my code worked.

```
//      for(i in settings.path){
            w.document.write('<link rel="stylesheet" href="'+settings.path+'">');
//      }
```

Now I'm applying the style to my prints!!! 
:)

Hope It helps!!!

**Comment by menusal** [comment]
@elmerdeve Thank you for your contribution but that way only could add one stylesheet, the problem was that the index is not assigned in the array. Already solved. Thank you very much for your contribution

**Comment by hfunescom** [comment]
Good! I'm happy I could help! :)
Best regards!!!
